### ISSUE TITLE
Braces and skew braces

### ISSUE THREAD

**Issue by vendramin** [vendramin/YB#12]
Do we need to set IsClassical if the brace is classical?

**Comment by olexandr-konovalov** [comment]
Yes. For braces read from a database, via `SetIsClassical(br,true)`. For those on which `IsClassical(br)` has been called, the system will take care of setting it via properties mechanism.

I suggest also to think about `IsClassicalBrace` to reduce the chance of name clashes.

**Comment by vendramin** [comment]
33e7f44db957d6c62548decec159f9f87cc1f3c1
