### ISSUE TITLE
SkewAGroup and SkewMGroup

### ISSUE THREAD

**Issue by vendramin** [vendramin/YB#14]
These are list of permutations. Should they be groups? Add support for the bijective 1-cocycle and for its inverse.

**Comment by olexandr-konovalov** [comment]
I think they should be groups, given by small generating sets. Then `SkewAGroup` (or `UnderlyingAdditiveGroup` - could be a synonym as well) will give more human-readable output. The ordering, which is used to perform operations, should be saved elsewhere.

Alternatively, `SkewAGroup` could be (documented or not?) attribute for ordering, and `UnderlyingAdditiveGroup` - documented attribute for the group. Need to think more.

**Comment by vendramin** [comment]
Closed by e1cf029d4005340651affeb0f1b79d6d444366dd
