### ISSUE TITLE
Some files in the database can be removed

### ISSUE THREAD

**Issue by vendramin** [vendramin/YB#41]
Remove data files for (skew)braces of size n, where Gcd(n,Phi(n))=1. 

The complete list of such numbers is:
1, 2, 3, 5, 7, 11, 13, 15, 17, 19, 23, 29, 31, 33, 35, 37, 41, 43, 47, 51, 53, 59, 61, 65, 67, 69, 71, 73, 77, 79, 83, 85, 87, 89, 91, 95, 97, 101, 103, 107, 109, 113, 115, 119, 123, 127.

**Comment by olexandr-konovalov** [comment]
This was done by @vendramin in 770d564d0d068ce3a56e4b578f8f59a54b2ef5bc but somehow n=1 and 5 were not removed - trying to figure out why.

**Comment by olexandr-konovalov** [comment]
The files for n=1 can't be removed, since they define global variables. Still, their size is negligible. The remaining n=5 case, overlooked earlier, is removed in #91
