### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by fingolfin** [vendramin/YB#78]
@alex-konovalov @vendramin can we make a new release of the YangBaxter packages? There are a ton of improvements in git which are not available to users.

Ideally first merge my PR #77. And perhaps Leandro wants his contact info updated?

I'd be happy to take care of the release for you, it should take me just a few minutes, don't hesitate to ask for it.

**Comment by fingolfin** [comment]
@vendramin ping

**Comment by vendramin** [comment]
I replied to Alexander's message. Yes, we can make a new release. He will take care of it.

**Comment by fingolfin** [comment]
@vendramin oh great, I wasn't aware you had separately discussed this with @alex-konovalov . In that case I look forward to him making that release :-)

**Comment by olexandr-konovalov** [comment]
@vendramin must have missed your reply, sorry! Can't see it in "participating" or "mentioned" tabs of GitHub notification centre. Anyway, I can make a new release :)

**Comment by vendramin** [comment]
Great, thanks!

**Comment by olexandr-konovalov** [comment]
@vendramin shall I put your contact details from https://vendramin.github.io/ ?

**Comment by vendramin** [comment]
Yes, sure.

**Comment by olexandr-konovalov** [comment]
@fingolfin almost there, hopefully @vendramin can comment on #80 shortly and it will fix tests in PackageDistro.

**Comment by vendramin** [comment]
I agree, thanks!

**Comment by olexandr-konovalov** [comment]
Done: https://github.com/gap-packages/YangBaxter/releases/tag/v0.10.0

**Comment by vendramin** [comment]
Sure!
