### ISSUE TITLE
Fix manual entry for Fix

### ISSUE THREAD

**Issue by olexandr-konovalov** [vendramin/YB#79]
Currently both 

* 3.4-3 IsMultipermutation 
* 3.4-4 Fix

state the same: "Returns: true if the skew brace obj has finite multipermutation level and false otherwise".

I guess the 2nd one is incorrect. @vendramin could you please provide the right one? Also, ideally we should rename "Fix", see #71.

**Comment by fingolfin** [comment]
@vendramin ping?

**Comment by vendramin** [comment]
Done!
