### ISSUE TITLE
BraceMultiplicativeGroup and AllSkewbraces

### ISSUE THREAD

**Issue by raemarina** [vendramin/YB#84]
We want to use the BraceMultiplicativeGroup function, but for some reason it gives the error "Error, Variable: 'BraceMultiplicativeGroup' must have a value not in any function at *stdin*:13". However, we noticed that this function is not displayed in the manual.
It would also be interesting to download all skewbraces on a certain group. But only found a mention of it on GitHub https://github.com/gap-packages/YangBaxter/tree/master/constr
We would like to have a similar AllBraces function for skewbraces, which returns an array of all skewbraces.
AllSkewbraces, AllSkewbracesByGroupId functions return information about skewbraces.

**Comment by vendramin** [comment]
The function for getting the underlying multiplicative group is UnderlyingMultiplicativeGroup. The package has no function to list all skew braces with a given multiplicative group. The folder constr is for the construction of the database.

**Comment by olexandr-konovalov** [comment]
@vendramin thanks - it seems that `UnderlyingMultiplicativeGroup` is undocumented though, can we add it?

**Comment by vendramin** [comment]
Done!

**Comment by olexandr-konovalov** [comment]
@vendramin would be nice to make a new release to include in the GAP new release expected very soon.
