### ISSUE TITLE
Regression against latest GAP master

### ISSUE THREAD

**Issue by fingolfin** [vendramin/YB#88]
With the latest GAP master from today, the YangBaxter test suite runs into a few errors:
```
########> Diff in GAPROOT/pkg/YangBaxter//tst/testinstall/skew.tst:271
# Input is:
IdSkewbrace(DirectProduct(br1,br2));
# Expected output:
[ 12, 22 ]
# But found:
[ 12, 23 ]
########
########> Diff in GAPROOT/pkg/YangBaxter/tst/testinstall/skew.tst:273
# Input is:
IdSkewbrace(DirectProduct(br2,br1));
# Expected output:
[ 12, 22 ]
# But found:
[ 12, 23 ]
########
########> Diff in GAPROOT/pkg/YangBaxter/tst/testinstall/skew.tst:281
# Input is:
IdBrace(DirectProduct(SmallBrace(4,2),SmallBrace(3,1),SmallBrace(3,1)));
# Expected output:
[ 36, 18 ]
# But found:
[ 36, fail ]
########
   23623 ms (1836 ms GC) and 10.6GB allocated for testinstall/skew.tst
testing: GAPROOT/pkg/YangBaxter/tst/testinstall/ybe.tst
      50 ms (34 ms GC) and 6.99MB allocated for testinstall/ybe.tst
testing: GAPROOT/pkg/YangBaxter/tst/yangbaxter01.tst
########> Diff in GAPROOT/pkg/YangBaxter/tst/yangbaxter01.tst:66
# Input is:
IsSolvable(br);
# Expected output:
true
# But found:
false
########
     601 ms (52 ms GC) and 185MB allocated for yangbaxter01.tst
```

I don't know which change exactly caused it, but the most likely "culprits" are https://github.com/gap-system/gap/pull/5216 and https://github.com/gap-system/gap/pull/5229.

One possibility is that one of these changes has a bug. But more likely seems to be that they merely reveal e.g. a problem with the YangBaxter test suite... E.g. if there is code which relies on `AsList(permgrp)` to return the same thing as `AsSet(permgrop)` (in particular: with elements in a specific order), then this code would be broken now.

**Comment by fingolfin** [comment]
@vendramin I submitted a fix in PR #89 (and it'd be great to get a release with that fix), but I find it quite concerning that the result of `DirectProduct` apparently was not well-defined before as it relied on the order of elements in `AsList(permgrp)`; but the order for `AsList` for *any* input is in general not  fixed, so this is dangerous. There seem to be several other places in the code here that use `AsList` and that look to me as if they might be at risk as well. E.g. the method for `SumOfTwoIdeals` in `lib/ideals.gi`, or the `SmallBrace` method `for a list of integers` use it. I can't judge if they use it "safely" or not, though.

Anyway: a new release with the fix in would be great. I am also happy to make it on your behalf (requires < 5 minutes of work for me), just let me know.

**Comment by vendramin** [comment]
Thanks. I will take a look. Will replacing AsList with AsSet solve these
problems?

**Comment by fingolfin** [comment]
For permutation groups, `AsSet` gives a stable, reproducible ordering, so one can rely on it.

**Comment by fingolfin** [comment]
@vendramin could you please either make a new release or permit me to make one?

**Comment by vendramin** [comment]
Yes, please do it. On 12 Dec 2022, at 09:06, Max Horn ***@***.***> wrote:﻿
@vendramin could you please either make a new release or permit me to make one?
