### ISSUE TITLE
Mistake in Dehornoyclass

### ISSUE THREAD

**Issue by VanAntwerpen** [vendramin/YB#94]
In the method DehornoyClass one should return lcm(tmp) not maximum(tmp).

**Comment by fingolfin** [comment]
This was already fixed by f8604b827319208967fc6218de3ea2ae89663de9, wasn't it?

**Comment by vendramin** [comment]
Was fixed again, because last time there was another small bug. On 12 Jan 2024, at 02:33, Max Horn ***@***.***> wrote:﻿
This was already fixed by f8604b8, wasn't it?

**Comment by olexandr-konovalov** [comment]
Fixed in f8604b827319208967fc6218de3ea2ae89663de9
